services:
  prestashop:
    image: prestashop/prestashop:8.2.3
    container_name: prestashop
    ports:
      - "8080:80"
    environment:
      - DB_SERVER=mysql
      - DB_NAME=prestashop
      - DB_USER=prestashop
      - DB_PASSWD=prestashop_password
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=localhost:8080
      - PS_FOLDER_ADMIN=admin-dev
      - PS_FOLDER_INSTALL=install-dev
      - PS_LANGUAGE=pl
      - PS_COUNTRY=PL
      - PS_DEV_MODE=1
      - PS_DEMO_MODE=0
      - PS_ENABLE_SSL=0
      - ADMIN_MAIL=admin@prestashop.local
      - ADMIN_PASSWD=Prestashop123!
    volumes:
      - ./prestashop-data:/var/www/html
    depends_on:
      - mysql
    networks:
      - prestashop-network

  mysql:
    image: mysql:8.0
    container_name: prestashop-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - prestashop-network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: prestashop-phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=prestashop
      - PMA_PASSWORD=prestashop_password
    depends_on:
      - mysql
    networks:
      - prestashop-network

volumes:
  mysql-data:

networks:
  prestashop-network:
    driver: bridge
